import json
import logging
import os
import re
from datetime import UTC, datetime
from pathlib import Path

from researchkit.agents.base import Result, SubAgent, SubAgentContext, Task
from researchkit.agents.str_replace_editor import WorkspaceStrReplaceEditor
from researchkit.agents.workspace_context import build_workspace_context_lines
from researchkit.config.schema import ProviderConfig
from researchkit.literature.asta_mcp_client import AstaMcpClient, AstaSnippet
from researchkit.literature.models import Paper
from researchkit.literature.search import papers_to_bibtex
from researchkit.literature.verify import verify_citations
from researchkit.memory.schema import PaperMemory
from researchkit.providers.registry import create_provider

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

RESEARCH_AGENT_SYSTEM_PROMPT = """\
You are ResearchKit's Research Agent.

You work as an internal agentic literature assistant with a ReAct loop:
1. think briefly about the next evidence-gathering step
2. call one or more tools
3. inspect the tool results
4. continue until you have enough evidence
5. call `finish` with the final response

Rules:
- Keep reasoning concise.
- Use tools instead of guessing.
- Use `str_replace_editor` only with the `view` command for read-only inspection of the paper workspace.
- Use `verify_citations` when the request asks for reference checking or when search results should be validated.
- Do not edit files and do not invent citations.
- Prefer targeted searches over broad repeated searches.
- Call `finish` once you have enough information. The `finish.summary` should be ready to show to the user.
"""

RESEARCH_AGENT_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "search_literature",
            "description": (
                "Search the literature using ASTA. Use this to discover papers, related work, "
                "seed papers, or supporting references."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Search query to run.",
                    },
                    "focus": {
                        "type": "string",
                        "description": (
                            "Optional focus note that sharpens the search, such as a method, "
                            "section goal, or evaluation angle."
                        ),
                    },
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "verify_citations",
            "description": (
                "Verify BibTeX citations and flag suspicious or hallucinated references."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "bibtex": {
                        "type": "string",
                        "description": "BibTeX entries to verify.",
                    },
                    "use_latest_search_bibtex": {
                        "type": "boolean",
                        "description": (
                            "When true, verify the latest BibTeX generated by `search_literature`."
                        ),
                    },
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "str_replace_editor",
            "description": (
                "Read a workspace file or list a workspace directory. This tool is read-only here "
                "and only supports the `view` command."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "command": {
                        "type": "string",
                        "enum": ["view"],
                        "description": "Editor command to run. Only `view` is allowed.",
                    },
                    "path": {
                        "type": "string",
                        "description": (
                            "Workspace-relative path by default. Absolute paths are allowed only "
                            "when they stay inside the workspace."
                        ),
                    },
                    "view_range": {
                        "type": "array",
                        "items": {"type": "integer"},
                        "minItems": 2,
                        "maxItems": 2,
                        "description": (
                            "Optional line range for `view`, formatted as [start_line, end_line]. "
                            "Use -1 for the end line to read through EOF."
                        ),
                    },
                },
                "required": ["command", "path"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "finish",
            "description": "Finish the loop and return the final response to the user.",
            "parameters": {
                "type": "object",
                "properties": {
                    "summary": {
                        "type": "string",
                        "description": "Final Markdown response for the user.",
                    },
                },
                "required": ["summary"],
            },
        },
    },
]


class ResearchAgent(SubAgent):
    name = "Research Agent"
    description = "Deep literature discovery with citation verification and BibTeX output"

    def __init__(self, config: ProviderConfig | None = None):
        self.config = config
        self.provider = create_provider(config) if config else None
        self.max_tool_iterations = max(config.max_tool_iterations, 1) if config else 8
        self.tool_output_max_chars = max(config.tool_output_max_chars, 200) if config else 12000

    async def execute(
        self,
        task: Task,
        memory: PaperMemory | None,
        context: SubAgentContext | None = None,
    ) -> Result:
        logger.info(
            "ResearchAgent execute start mode=%s task_type=%s has_memory=%s has_context=%s task=%r",
            "react" if self.provider is not None else "single_pass",
            task.type,
            memory is not None,
            context is not None,
            self._truncate_text(task.description.strip(), 240),
        )
        if self.provider is None:
            result = await self._execute_single_pass(task, memory)
            logger.info(
                "ResearchAgent execute completed mode=single_pass status=%s artifacts=%d content_chars=%d",
                result.status,
                len(result.artifacts),
                len(result.content),
            )
            return result

        try:
            result = await self._execute_react_loop(task, memory, context)
            logger.info(
                "ResearchAgent execute completed mode=react status=%s artifacts=%d content_chars=%d",
                result.status,
                len(result.artifacts),
                len(result.content),
            )
            return result
        except Exception as exc:  # noqa: BLE001
            logger.exception("ResearchAgent ReAct loop failed: %s", exc)
            fallback = await self._execute_single_pass(task, memory)
            fallback.content += (
                "\n\n- ReAct loop failed and the agent returned a deterministic fallback summary."
            )
            logger.info(
                "ResearchAgent execute completed mode=react_fallback status=%s artifacts=%d content_chars=%d",
                fallback.status,
                len(fallback.artifacts),
                len(fallback.content),
            )
            return fallback

    async def _execute_react_loop(
        self,
        task: Task,
        memory: PaperMemory | None,
        context: SubAgentContext | None,
    ) -> Result:
        state = {
            "artifacts": [],
            "latest_search_bibtex": "",
        }
        logger.info(
            "ResearchAgent ReAct start max_iterations=%d has_workspace_context=%s",
            self.max_tool_iterations,
            bool(context and context.workspace_path),
        )
        messages = [
            {"role": "system", "content": RESEARCH_AGENT_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": self._build_user_message(task, memory, context),
            },
        ]

        for iteration in range(self.max_tool_iterations):
            logger.info(
                "ResearchAgent ReAct iteration start iteration=%d/%d messages=%d artifacts=%d",
                iteration + 1,
                self.max_tool_iterations,
                len(messages),
                len(state["artifacts"]),
            )
            tool_response = await self.provider.complete_with_tools(messages, RESEARCH_AGENT_TOOLS)
            assistant_content = str(tool_response.get("content") or "").strip()
            tool_calls = tool_response.get("tool_calls") or []
            logger.info(
                "ResearchAgent ReAct iteration received iteration=%d tool_calls=%d assistant_chars=%d",
                iteration + 1,
                len(tool_calls),
                len(assistant_content),
            )
            if assistant_content:
                logger.info(
                    "ResearchAgent ReAct assistant content iteration=%d content=%s",
                    iteration + 1,
                    self._truncate(assistant_content, 2000),
                )
            assistant_record = assistant_content or (
                f"Calling {len(tool_calls)} research tool"
                f"{'' if len(tool_calls) == 1 else 's'}."
                if tool_calls
                else ""
            )
            if assistant_record:
                messages.append({"role": "assistant", "content": assistant_record})

            if not tool_calls:
                summary = assistant_content or self._build_fallback_summary(
                    task, state["artifacts"]
                )
                logger.info(
                    "ResearchAgent ReAct completed iteration=%d reason=no_tool_calls artifacts=%d summary_chars=%d",
                    iteration + 1,
                    len(state["artifacts"]),
                    len(summary),
                )
                return Result(
                    status="completed",
                    content=self._format_final_content(summary),
                    artifacts=list(state["artifacts"]),
                )

            for index, tool_call in enumerate(tool_calls, start=1):
                func_name = str(tool_call.get("function", {}).get("name") or "").strip()
                raw_args = tool_call.get("function", {}).get("arguments", "{}")
                logger.info(
                    "ResearchAgent tool call start iteration=%d call=%d/%d tool=%s args=%s",
                    iteration + 1,
                    index,
                    len(tool_calls),
                    func_name,
                    self._truncate(str(raw_args), 1200),
                )
                try:
                    args = json.loads(raw_args) if isinstance(raw_args, str) else dict(raw_args)
                except (TypeError, ValueError, json.JSONDecodeError):
                    error_text = (
                        f"Tool call `{func_name}` has invalid JSON arguments: {raw_args}"
                    )
                    logger.warning(
                        "ResearchAgent tool call invalid arguments iteration=%d tool=%s raw_args=%s",
                        iteration + 1,
                        func_name,
                        self._truncate(str(raw_args), 1200),
                    )
                    messages.append(
                        {
                            "role": "user",
                            "content": self._build_tool_result_message(
                                func_name=func_name,
                                tool_result={"error": error_text},
                                visible_text=error_text,
                            ),
                        }
                    )
                    continue

                execution = await self._execute_react_tool(
                    func_name=func_name,
                    args=args,
                    task=task,
                    memory=memory,
                    context=context,
                    state=state,
                )
                logger.info(
                    "ResearchAgent tool call completed iteration=%d call=%d/%d tool=%s error=%s finished=%s visible_chars=%d artifacts=%d",
                    iteration + 1,
                    index,
                    len(tool_calls),
                    func_name,
                    bool(execution["tool_result"].get("error")),
                    execution["finished_content"] is not None,
                    len(execution["visible_text"]),
                    len(state["artifacts"]),
                )
                logger.info(
                    "ResearchAgent tool call result iteration=%d call=%d/%d tool=%s tool_result=%s",
                    iteration + 1,
                    index,
                    len(tool_calls),
                    func_name,
                    self._truncate(self._safe_json_dumps(execution["tool_result"]), 4000),
                )
                if execution["visible_text"]:
                    logger.info(
                        "ResearchAgent tool call visible output iteration=%d call=%d/%d tool=%s output=%s",
                        iteration + 1,
                        index,
                        len(tool_calls),
                        func_name,
                        self._truncate(execution["visible_text"], 2000),
                    )
                messages.append(
                    {
                        "role": "user",
                        "content": self._build_tool_result_message(
                            func_name=func_name,
                            tool_result=execution["tool_result"],
                            visible_text=execution["visible_text"],
                        ),
                    }
                )
                if execution["finished_content"] is not None:
                    logger.info(
                        "ResearchAgent ReAct finished via tool iteration=%d tool=%s summary_chars=%d",
                        iteration + 1,
                        func_name,
                        len(execution["finished_content"]),
                    )
                    return Result(
                        status="completed",
                        content=self._format_final_content(execution["finished_content"]),
                        artifacts=list(state["artifacts"]),
                    )

        logger.info(
            "ResearchAgent ReAct exhausted max_iterations=%d artifacts=%d",
            self.max_tool_iterations,
            len(state["artifacts"]),
        )
        return Result(
            status="completed",
            content=self._format_final_content(
                self._build_fallback_summary(task, state["artifacts"], exhausted=True)
            ),
            artifacts=list(state["artifacts"]),
        )

    async def _execute_react_tool(
        self,
        *,
        func_name: str,
        args: dict,
        task: Task,
        memory: PaperMemory | None,
        context: SubAgentContext | None,
        state: dict,
    ) -> dict:
        if func_name == "search_literature":
            query = str(args.get("query") or "").strip() or self._build_search_query(
                task.description, memory
            )
            focus = str(args.get("focus") or "").strip()
            logger.info(
                "ResearchAgent search_literature requested query=%r focus=%r",
                query,
                self._truncate_text(focus, 160) if focus else "",
            )
            if not query:
                message = "search_literature requires a non-empty query."
                return self._tool_error(message)

            search_description = task.description.strip()
            if focus:
                search_description += f"\n\nFocus: {focus}"

            asta_api_key = (self.config.asta_api_key if self.config else "") or ""
            asta_mcp_url = (self.config.asta_mcp_url if self.config else "") or ""
            try:
                papers, snippets = await self._search_with_asta(
                    query,
                    search_description,
                    memory,
                    asta_api_key=asta_api_key,
                    asta_mcp_url=asta_mcp_url,
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning("Research search failed for query=%r: %s", query, exc)
                return self._tool_error(f"Search failed for query `{query}`: {exc}")

            top_papers = papers[:10]
            bibtex_text = papers_to_bibtex(top_papers) if top_papers else ""
            artifact = {
                "type": "literature_search_result",
                "query": query,
                "result_count": len(papers),
                "papers": [paper.to_dict() for paper in top_papers],
                "bibtex": bibtex_text,
            }
            state["artifacts"].append(artifact)
            state["latest_search_bibtex"] = bibtex_text
            logger.info(
                "ResearchAgent search_literature completed query=%r papers=%d snippets=%d bibtex_chars=%d",
                query,
                len(papers),
                len(snippets),
                len(bibtex_text),
            )
            return {
                "tool_result": {
                    "query": query,
                    "result_count": len(papers),
                    "papers": [self._paper_preview(paper) for paper in top_papers[:5]],
                    "snippets": [self._snippet_preview(snippet) for snippet in snippets[:3]],
                    "bibtex": bibtex_text,
                    "artifacts": [artifact],
                },
                "visible_text": self._summarize_search_artifact(artifact, snippets),
                "finished_content": None,
            }

        if func_name == "verify_citations":
            bibtex = str(args.get("bibtex") or "").strip()
            use_latest_search_bibtex = bool(args.get("use_latest_search_bibtex"))
            if use_latest_search_bibtex and not bibtex:
                bibtex = str(state.get("latest_search_bibtex") or "").strip()
            logger.info(
                "ResearchAgent verify_citations requested use_latest_search_bibtex=%s bibtex_chars=%d",
                use_latest_search_bibtex,
                len(bibtex),
            )
            if not bibtex:
                message = "Verification skipped: no BibTeX entries were provided or generated."
                return self._tool_error(message)

            try:
                report = verify_citations(bibtex)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Citation verification failed: %s", exc)
                return self._tool_error(f"Citation verification failed: {exc}")

            report_dict = report.to_dict()
            summary = report_dict.get("summary", {})
            artifact = {
                "type": "citation_verification_result",
                "summary": summary,
                "results": report_dict.get("results", []),
            }
            state["artifacts"].append(artifact)
            logger.info(
                "ResearchAgent verify_citations completed verified=%s suspicious=%s hallucinated=%s skipped=%s",
                summary.get("verified", 0),
                summary.get("suspicious", 0),
                summary.get("hallucinated", 0),
                summary.get("skipped", 0),
            )
            return {
                "tool_result": {
                    "summary": summary,
                    "flagged": [
                        item
                        for item in report_dict.get("results", [])
                        if isinstance(item, dict)
                        and item.get("status") in {"suspicious", "hallucinated"}
                    ][:5],
                    "artifacts": [artifact],
                },
                "visible_text": self._summarize_verification_artifact(artifact),
                "finished_content": None,
            }

        if func_name == "str_replace_editor":
            logger.info(
                "ResearchAgent str_replace_editor requested command=%s path=%s view_range=%s",
                str(args.get("command") or "").strip(),
                str(args.get("path") or "").strip(),
                args.get("view_range"),
            )
            try:
                tool_result = self._execute_read_only_editor(
                    context=context,
                    command=str(args.get("command") or "").strip(),
                    path=str(args.get("path") or "").strip(),
                    view_range=args.get("view_range"),
                )
            except Exception as exc:  # noqa: BLE001
                return self._tool_error(str(exc))
            logger.info(
                "ResearchAgent str_replace_editor completed path=%s status=%s preview_chars=%d",
                tool_result.get("path"),
                tool_result.get("status"),
                len(str(tool_result.get("preview") or "")),
            )
            return {
                "tool_result": tool_result,
                "visible_text": str(tool_result.get("preview") or ""),
                "finished_content": None,
            }

        if func_name == "finish":
            summary = str(args.get("summary") or "").strip()
            logger.info(
                "ResearchAgent finish requested summary_chars=%d",
                len(summary),
            )
            return {
                "tool_result": {"status": "completed"},
                "visible_text": summary,
                "finished_content": summary or self._build_fallback_summary(
                    task, state["artifacts"]
                ),
            }

        return self._tool_error(f"Unsupported research tool: {func_name}")

    async def _execute_single_pass(self, task: Task, memory: PaperMemory | None) -> Result:
        description = task.description.strip()
        query = self._build_search_query(description, memory)
        bibtex_block = self._extract_bibtex(description)
        verify_intent = self._is_verification_request(description)
        should_search = self._should_run_search(description, bibtex_block)
        should_verify = verify_intent or bool(bibtex_block)

        artifacts: list[dict] = []
        lines = ["### Research Agent"]
        logger.info(
            "ResearchAgent single-pass start query=%r should_search=%s should_verify=%s has_bibtex=%s",
            query,
            should_search,
            should_verify,
            bool(bibtex_block),
        )

        asta_api_key = (self.config.asta_api_key if self.config else "") or ""
        asta_mcp_url = (self.config.asta_mcp_url if self.config else "") or ""

        searched_papers: list[Paper] = []
        if should_search and query:
            logger.info("ResearchAgent single-pass search start query=%r", query)
            try:
                searched_papers, snippets = await self._search_with_asta(
                    query,
                    description,
                    memory,
                    asta_api_key=asta_api_key,
                    asta_mcp_url=asta_mcp_url,
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning("Research search failed for query=%r: %s", query, exc)
                lines.append(f"- Search failed for query `{query}`: {exc}")
            else:
                top_papers = searched_papers[:10]
                bibtex_text = papers_to_bibtex(top_papers) if top_papers else ""
                artifact = {
                    "type": "literature_search_result",
                    "query": query,
                    "result_count": len(searched_papers),
                    "papers": [paper.to_dict() for paper in top_papers],
                    "bibtex": bibtex_text,
                }
                artifacts.append(artifact)
                logger.info(
                    "ResearchAgent single-pass search completed query=%r papers=%d snippets=%d bibtex_chars=%d",
                    query,
                    len(searched_papers),
                    len(snippets),
                    len(bibtex_text),
                )
                lines.append(self._summarize_search_artifact(artifact, snippets))

        bibtex_for_verify = bibtex_block
        if should_verify and not bibtex_for_verify and searched_papers:
            bibtex_for_verify = papers_to_bibtex(searched_papers[:20])

        if should_verify:
            if not bibtex_for_verify:
                logger.info("ResearchAgent single-pass verification skipped reason=no_bibtex")
                lines.append("- Verification skipped: no BibTeX entries were provided or generated.")
            else:
                logger.info(
                    "ResearchAgent single-pass verification start bibtex_chars=%d",
                    len(bibtex_for_verify),
                )
                try:
                    report = verify_citations(bibtex_for_verify)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("Citation verification failed: %s", exc)
                    lines.append(f"- Citation verification failed: {exc}")
                else:
                    report_dict = report.to_dict()
                    artifact = {
                        "type": "citation_verification_result",
                        "summary": report_dict.get("summary", {}),
                        "results": report_dict.get("results", []),
                    }
                    artifacts.append(artifact)
                    logger.info(
                        "ResearchAgent single-pass verification completed verified=%s suspicious=%s hallucinated=%s skipped=%s",
                        artifact["summary"].get("verified", 0),
                        artifact["summary"].get("suspicious", 0),
                        artifact["summary"].get("hallucinated", 0),
                        artifact["summary"].get("skipped", 0),
                    )
                    lines.append(self._summarize_verification_artifact(artifact))

        if len(lines) == 1:
            lines.append("- No actionable literature step could be derived from this request.")

        logger.info(
            "ResearchAgent single-pass completed artifacts=%d content_lines=%d",
            len(artifacts),
            len(lines),
        )
        return Result(
            status="completed",
            content="\n".join(lines),
            artifacts=artifacts,
        )

    def _tool_error(self, message: str) -> dict:
        return {
            "tool_result": {"error": message},
            "visible_text": message,
            "finished_content": None,
        }

    def _build_user_message(
        self,
        task: Task,
        memory: PaperMemory | None,
        context: SubAgentContext | None,
    ) -> str:
        derived_query = self._build_search_query(task.description, memory)
        bibtex_block = self._extract_bibtex(task.description)
        lines = ["Task:", task.description.strip()]
        if derived_query:
            lines.append(f"Derived search query: {derived_query}")
        if bibtex_block:
            lines.append("Request contains BibTeX that may need verification.")
        if context and context.workspace_path:
            lines.extend(
                build_workspace_context_lines(
                    context.workspace_path,
                    active_file=context.file_path,
                )
            )
        if context and context.file_path:
            lines.append(f"Active file: {context.file_path}")
        if context and context.selected_text:
            selection = self._truncate_text(context.selected_text, 300)
            lines.append(f"Selected text: {selection}")
        if context and context.cursor_line is not None:
            lines.append(f"Cursor line: {context.cursor_line}")
        if memory and memory.paper_summary:
            lines.append(f"Paper summary: {self._truncate_text(memory.paper_summary, 400)}")
        if memory and memory.research_questions:
            lines.append("Research questions:")
            lines.extend(f"- {question}" for question in memory.research_questions[:5])
        if memory and memory.contributions:
            lines.append("Contributions:")
            lines.extend(f"- {contribution}" for contribution in memory.contributions[:5])
        if memory and memory.citations:
            lines.append("Known citations:")
            for citation in memory.citations[:10]:
                venue = f" · {citation.venue}" if citation.venue else ""
                year = f" ({citation.year})" if citation.year else ""
                lines.append(f"- {citation.key}: {citation.title}{year}{venue}")
        if memory and memory.structure_map:
            lines.append("Paper structure:")
            for section in memory.structure_map[:10]:
                lines.append(
                    f"- L{section.level} {section.name} [{section.status}]"
                    + (f" in {section.file_path}" if section.file_path else "")
                )
        return "\n".join(lines)

    def _build_tool_result_message(
        self,
        *,
        func_name: str,
        tool_result: dict,
        visible_text: str,
    ) -> str:
        lines = [f"Tool `{func_name}` result:"]
        if tool_result.get("error"):
            lines.append(f"Error: {tool_result['error']}")
        else:
            serialized = self._safe_json_dumps(tool_result)
            lines.append(
                f"```json\n{self._truncate(serialized, self.tool_output_max_chars)}\n```"
            )
        if visible_text:
            lines.append("Visible output:")
            lines.append(
                f"```text\n{self._truncate(visible_text, self.tool_output_max_chars)}\n```"
            )
        return "\n".join(lines)

    def _format_final_content(self, content: str) -> str:
        stripped = content.strip()
        if not stripped:
            stripped = "- No actionable literature step could be derived from this request."
        if stripped.startswith("### "):
            return stripped
        return f"### Research Agent\n{stripped}"

    def _build_fallback_summary(
        self,
        task: Task,
        artifacts: list[dict],
        *,
        exhausted: bool = False,
    ) -> str:
        lines = ["### Research Agent"]
        if exhausted:
            lines.append("- Reached the research tool iteration limit and returning the best partial summary available.")

        search_artifact = next(
            (
                artifact
                for artifact in reversed(artifacts)
                if isinstance(artifact, dict)
                and artifact.get("type") == "literature_search_result"
            ),
            None,
        )
        verification_artifact = next(
            (
                artifact
                for artifact in reversed(artifacts)
                if isinstance(artifact, dict)
                and artifact.get("type") == "citation_verification_result"
            ),
            None,
        )

        if search_artifact:
            lines.append(self._summarize_search_artifact(search_artifact, []))
        if verification_artifact:
            lines.append(self._summarize_verification_artifact(verification_artifact))
        if len(lines) == 1 or (exhausted and len(lines) == 2):
            lines.append(
                "- No completed literature actions were captured; use a follow-up request to continue the investigation."
            )
            lines.append(f"- Original request: {task.description.strip()}")
        return "\n".join(lines)

    def _execute_read_only_editor(
        self,
        *,
        context: SubAgentContext | None,
        command: str,
        path: str,
        view_range: object,
    ) -> dict:
        workspace_path = context.workspace_path if context else None
        if not workspace_path:
            raise ValueError("Workspace access is unavailable for this request.")
        if command != "view":
            raise ValueError("ResearchAgent only allows `str_replace_editor` with the `view` command.")
        editor = WorkspaceStrReplaceEditor(
            workspace_path=workspace_path,
            history=None,
            max_response_chars=self.tool_output_max_chars,
        )
        result = editor.execute(
            command="view",
            path=path,
            view_range=view_range if isinstance(view_range, list) else None,
        )
        workspace_root = Path(os.path.realpath(workspace_path))
        normalized_path = self._normalize_workspace_editor_path(result.path, workspace_root)
        return {
            "command": result.command,
            "path": normalized_path,
            "status": result.status,
            "summary": result.summary,
            "metadata": result.metadata,
            "preview": result.output,
        }

    @staticmethod
    def _normalize_workspace_editor_path(path: str, workspace_root: Path) -> str:
        real_path = Path(os.path.realpath(path))
        real_root = Path(os.path.realpath(str(workspace_root)))
        if real_path == real_root:
            return "."
        return real_path.relative_to(real_root).as_posix()

    @staticmethod
    def _safe_json_dumps(value: object) -> str:
        try:
            return json.dumps(value, ensure_ascii=False, default=str)
        except (TypeError, ValueError):
            return str(value)

    @staticmethod
    def _truncate(value: str, max_chars: int) -> str:
        if len(value) <= max_chars:
            return value
        return value[: max_chars - 16] + "\n...[truncated]"

    @staticmethod
    def _paper_preview(paper: Paper) -> dict:
        return {
            "paper_id": paper.paper_id,
            "title": paper.title,
            "year": paper.year,
            "venue": paper.venue,
            "citation_count": paper.citation_count,
            "doi": paper.doi,
            "url": paper.url,
        }

    @staticmethod
    def _snippet_preview(snippet: AstaSnippet) -> dict:
        return {
            "paper_id": snippet.paper_id,
            "paper_title": snippet.paper_title,
            "text": ResearchAgent._truncate_text(snippet.text, 220),
        }

    def _summarize_search_artifact(
        self,
        artifact: dict,
        snippets: list[AstaSnippet] | list[dict],
    ) -> str:
        lines = [
            f"- Found **{artifact.get('result_count', 0)}** papers for query: `{artifact.get('query', '')}`."
        ]
        papers = artifact.get("papers") or []
        if papers:
            lines.append("- Top results:")
            for paper in papers[:5]:
                if isinstance(paper, Paper):
                    title = paper.title
                    year = paper.year or "n/a"
                    venue = paper.venue or "Unknown venue"
                    cites = paper.citation_count
                else:
                    title = str(paper.get("title", "Untitled"))
                    year = paper.get("year") or "n/a"
                    venue = paper.get("venue") or "Unknown venue"
                    cites = paper.get("citation_count")
                lines.append(f"  - {title} ({year}) | {venue} | cites={cites}")
        if snippets:
            lines.append("- Matching snippets:")
            for snippet in snippets[:3]:
                if isinstance(snippet, AstaSnippet):
                    title = snippet.paper_title or snippet.paper_id or "Untitled"
                    text = snippet.text
                else:
                    title = str(snippet.get("paper_title") or snippet.get("paper_id") or "Untitled")
                    text = str(snippet.get("text") or "")
                lines.append(f"  - {title}: {self._truncate_text(text, 220)}")
        if artifact.get("bibtex"):
            lines.append("- Generated BibTeX for top results.")
        return "\n".join(lines)

    @staticmethod
    def _summarize_verification_artifact(artifact: dict) -> str:
        summary = artifact.get("summary", {})
        lines = [
            "- Citation verification:"
            f" verified={summary.get('verified', 0)},"
            f" suspicious={summary.get('suspicious', 0)},"
            f" hallucinated={summary.get('hallucinated', 0)},"
            f" skipped={summary.get('skipped', 0)},"
            f" integrity_score={summary.get('integrity_score', 1.0)}."
        ]
        suspicious = [
            item
            for item in artifact.get("results", [])
            if isinstance(item, dict)
            and item.get("status") in {"suspicious", "hallucinated"}
        ]
        if suspicious:
            lines.append("- Flagged references:")
            for item in suspicious[:5]:
                title = str(item.get("title", "Untitled"))
                status = str(item.get("status", "unknown"))
                details = str(item.get("details", ""))
                lines.append(f"  - [{status}] {title} | {details}")
        return "\n".join(lines)

    def _create_asta_client(self, *, asta_api_key: str, asta_mcp_url: str) -> AstaMcpClient:
        return AstaMcpClient(
            asta_api_key,
            server_url=asta_mcp_url,
        )

    async def _search_with_asta(
        self,
        query: str,
        description: str,
        memory: PaperMemory | None,
        *,
        asta_api_key: str,
        asta_mcp_url: str,
    ) -> tuple[list[Paper], list[AstaSnippet]]:
        if not asta_api_key.strip():
            raise RuntimeError("ASTA API key is not configured.")

        publication_date_range = self._build_publication_date_range(description, memory)
        title_queries = self._extract_title_queries(description, memory)
        author_queries = self._extract_author_queries(description)
        logger.info(
            "ResearchAgent ASTA search start query=%r publication_date_range=%s title_queries=%d author_queries=%d",
            query,
            publication_date_range,
            len(title_queries),
            len(author_queries),
        )

        async with self._create_asta_client(
            asta_api_key=asta_api_key,
            asta_mcp_url=asta_mcp_url,
        ) as asta:
            primary_results = await asta.search_papers_by_relevance(
                query,
                limit=12,
                publication_date_range=publication_date_range,
            )
            logger.info(
                "ResearchAgent ASTA relevance search completed query=%r papers=%d",
                query,
                len(primary_results),
            )

            title_results: list[Paper] = []
            for title in title_queries[:8]:
                title_results.extend(
                    await asta.search_paper_by_title(
                        title,
                        publication_date_range=publication_date_range,
                    )
                )
            logger.info(
                "ResearchAgent ASTA title search completed queries=%d papers=%d",
                min(len(title_queries), 8),
                len(title_results),
            )

            author_results: list[Paper] = []
            for name in author_queries[:2]:
                authors = await asta.search_authors_by_name(name, limit=3)
                for author in authors[:2]:
                    author_id = str(author.get("author_id") or "").strip()
                    if not author_id:
                        continue
                    author_results.extend(
                        await asta.get_author_papers(
                            author_id,
                            limit=6,
                            publication_date_range=publication_date_range,
                        )
                    )
            logger.info(
                "ResearchAgent ASTA author expansion completed queries=%d papers=%d",
                min(len(author_queries), 2),
                len(author_results),
            )

            combined = self._deduplicate_papers(primary_results + title_results + author_results)
            logger.info(
                "ResearchAgent ASTA deduplicated initial results papers=%d",
                len(combined),
            )
            enriched = await self._enrich_papers(asta, combined[:8])
            logger.info(
                "ResearchAgent ASTA enrichment completed requested=%d enriched=%d",
                min(len(combined), 8),
                len(enriched),
            )

            citation_results: list[Paper] = []
            for paper in enriched[:3]:
                citation_results.extend(
                    await asta.get_citations(
                        paper.paper_id,
                        limit=6,
                        publication_date_range=publication_date_range,
                    )
                )
            logger.info(
                "ResearchAgent ASTA citation expansion completed seeds=%d papers=%d",
                min(len(enriched), 3),
                len(citation_results),
            )

            merged = self._deduplicate_papers(enriched + combined[8:] + citation_results)

            snippet_ids = [paper.paper_id for paper in merged[:10] if paper.paper_id]
            snippets = await asta.snippet_search(query, limit=5, paper_ids=snippet_ids or None)
            logger.info(
                "ResearchAgent ASTA snippet search completed candidate_ids=%d snippets=%d merged=%d returned=%d",
                len(snippet_ids),
                len(snippets),
                len(merged),
                len(merged[:20]),
            )

            return merged[:20], snippets

    async def _enrich_papers(self, asta: AstaMcpClient, papers: list[Paper]) -> list[Paper]:
        logger.info("ResearchAgent ASTA enrichment start papers=%d", len(papers))
        enriched: list[Paper] = []
        for paper in papers:
            try:
                detailed = await asta.get_paper(paper.paper_id)
            except Exception as exc:  # noqa: BLE001
                logger.info("ASTA get_paper failed for %s: %s", paper.paper_id, exc)
                detailed = None
            enriched.append(detailed or paper)
        logger.info("ResearchAgent ASTA enrichment finished papers=%d", len(enriched))
        return enriched

    @staticmethod
    def _truncate_text(text: str, limit: int) -> str:
        text = " ".join(text.split())
        if len(text) <= limit:
            return text
        return text[: limit - 3].rstrip() + "..."

    @staticmethod
    def _deduplicate_papers(papers: list[Paper]) -> list[Paper]:
        deduped: list[Paper] = []
        seen: set[str] = set()
        for paper in papers:
            keys = [
                paper.doi.lower().strip() if paper.doi else "",
                paper.arxiv_id.lower().strip() if paper.arxiv_id else "",
                re.sub(r"\W+", "", paper.title.lower()),
            ]
            if any(key and key in seen for key in keys):
                continue
            deduped.append(paper)
            seen.update(key for key in keys if key)
        return deduped

    @staticmethod
    def _build_publication_date_range(text: str, memory: PaperMemory | None) -> str:
        current_date = datetime.now(UTC).date()
        lowered = text.lower()
        years = [int(match) for match in re.findall(r"\b(19\d{2}|20\d{2})\b", text)]
        if len(years) >= 2:
            start = min(years)
            end = max(years)
            return f"{start}:{end}"
        if len(years) == 1:
            year = years[0]
            if any(token in lowered for token in ("since", "after", "from")):
                return f"{year}:"
            return str(year)

        if any(
            token in lowered
            for token in ("recent", "latest", "newest", "state of the art", "sota")
        ):
            return f"{current_date.year - 3}:"

        venue_year = ResearchAgent._extract_memory_year(memory)
        if venue_year is not None:
            return f"{max(venue_year - 3, 2000)}:"

        return f"{current_date.year - 5}:"

    @staticmethod
    def _extract_memory_year(memory: PaperMemory | None) -> int | None:
        if not memory or not memory.venue:
            return None

        raw_year = None
        if isinstance(memory.venue, dict):
            raw_year = memory.venue.get("year")
        else:
            raw_year = getattr(memory.venue, "year", None)

        if raw_year is None:
            return None

        if isinstance(raw_year, int):
            return raw_year

        raw_text = str(raw_year).strip()
        if raw_text.isdigit():
            return int(raw_text)

        return None

    @staticmethod
    def _extract_title_queries(text: str, memory: PaperMemory | None = None) -> list[str]:
        titles: list[str] = []
        for match in re.findall(r'"([^"\n]{12,200})"', text):
            value = match.strip()
            if value:
                titles.append(value)
        for match in re.findall(r"'([^'\n]{12,200})'", text):
            value = match.strip()
            if value:
                titles.append(value)

        explicit = re.search(r"title\s*:\s*(.+)", text, flags=re.IGNORECASE)
        if explicit:
            value = explicit.group(1).strip()
            if value:
                titles.append(value[:240])

        if memory and memory.citations:
            citation_map = {
                citation.key.lower(): citation.title.strip()
                for citation in memory.citations
                if citation.key and citation.title.strip()
            }
            for key in ResearchAgent._extract_citation_keys(text):
                title = citation_map.get(key.lower())
                if title:
                    titles.append(title[:240])

        cleaned: list[str] = []
        seen: set[str] = set()
        for title in titles:
            normalized = " ".join(title.split()).strip(" .,:;")
            if len(normalized) < 12:
                continue
            lowered = normalized.lower()
            if lowered in seen:
                continue
            seen.add(lowered)
            cleaned.append(normalized)
        return cleaned

    @staticmethod
    def _extract_author_queries(text: str) -> list[str]:
        candidates: list[str] = []
        explicit = re.search(r"authors?\s*:\s*([^\n]+)", text, flags=re.IGNORECASE)
        if explicit:
            candidates.extend(re.split(r",| and ", explicit.group(1)))

        by_matches = re.findall(
            r"\bby\s+([A-Z][A-Za-z.\-']+(?:\s+[A-Z][A-Za-z.\-']+){0,3})",
            text,
        )
        candidates.extend(by_matches)

        cleaned: list[str] = []
        seen: set[str] = set()
        for candidate in candidates:
            value = " ".join(candidate.split()).strip(" .,:;")
            if len(value.split()) < 2:
                continue
            lowered = value.lower()
            if lowered in seen:
                continue
            seen.add(lowered)
            cleaned.append(value)
        return cleaned

    @staticmethod
    def _extract_citation_keys(text: str) -> list[str]:
        matches = re.findall(r"\b([A-Za-z][A-Za-z0-9_-]*\d{4}[A-Za-z0-9_-]*)\b", text)
        keys: list[str] = []
        seen: set[str] = set()
        for match in matches:
            lowered = match.lower()
            if lowered in seen:
                continue
            seen.add(lowered)
            keys.append(match)
        return keys

    @staticmethod
    def _extract_bibtex(text: str) -> str:
        fenced = re.search(r"```(?:bibtex)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
        if fenced and "@" in fenced.group(1):
            return fenced.group(1).strip()
        if "@" in text and re.search(r"@\w+\s*{", text):
            return text.strip()
        return ""

    @staticmethod
    def _is_verification_request(text: str) -> bool:
        lowered = text.lower()
        keywords = (
            "verify",
            "hallucinated",
            "citation integrity",
            "fact-check citation",
            "check references",
            "validate references",
        )
        return any(keyword in lowered for keyword in keywords)

    @staticmethod
    def _should_run_search(text: str, bibtex_block: str) -> bool:
        lowered = text.lower()
        search_keywords = (
            "search",
            "find",
            "related work",
            "literature",
            "survey",
            "seed paper",
            "paper discovery",
        )
        verify_only = any(
            phrase in lowered
            for phrase in ("verify", "validate references", "check references")
        )
        if verify_only and bibtex_block and not any(k in lowered for k in search_keywords):
            return False
        return True

    @staticmethod
    def _build_search_query(text: str, memory: PaperMemory | None) -> str:
        stripped = text.strip()
        explicit = re.search(r"query\s*:\s*(.+)", stripped, flags=re.IGNORECASE)
        if explicit:
            return explicit.group(1).strip()[:240]

        title_queries = ResearchAgent._extract_title_queries(stripped, memory)
        if title_queries:
            return " ; ".join(title_queries[:3])[:240]

        without_code = re.sub(r"```.*?```", " ", stripped, flags=re.DOTALL)
        without_bib = re.sub(r"@\w+\s*{[^}]*}", " ", without_code)
        collapsed = " ".join(without_bib.split())
        if collapsed:
            return collapsed[:240]

        if memory:
            if memory.research_questions:
                return memory.research_questions[0][:240]
            if memory.paper_summary:
                return memory.paper_summary[:240]
        return ""
